/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IConversion } from "./IConversion";
export type { IEzToken } from "./IEzToken";
export type { IEzVault } from "./IEzVault";
