/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IConversion,
  IConversionInterface,
} from "../../../../contracts/interfaces/v1/IConversion";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IConversion__factory {
  static readonly abi = _abi;
  static createInterface(): IConversionInterface {
    return new utils.Interface(_abi) as IConversionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConversion {
    return new Contract(address, _abi, signerOrProvider) as IConversion;
  }
}
