/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEzVault,
  IEzVaultInterface,
} from "../../../../contracts/interfaces/v1/IEzVault";

const _abi = [
  {
    inputs: [],
    name: "convertDownPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "interestRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "leverage",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "matchedA",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pooledA",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum IEzVault.TYPE",
        name: "type_",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "channel_",
        type: "uint8",
      },
      {
        components: [
          {
            internalType: "address",
            name: "sellToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "buyToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "sellAmount",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "swapCallData",
            type: "bytes",
          },
        ],
        internalType: "struct SwapQuote[]",
        name: "quotes_",
        type: "tuple[]",
      },
    ],
    name: "purchase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum IEzVault.TYPE",
        name: "type_",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "channel_",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "qty_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "token_",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "sellToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "buyToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "sellAmount",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "swapCallData",
            type: "bytes",
          },
        ],
        internalType: "struct SwapQuote",
        name: "quote_",
        type: "tuple",
      },
    ],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalNetWorth",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEzVault__factory {
  static readonly abi = _abi;
  static createInterface(): IEzVaultInterface {
    return new utils.Interface(_abi) as IEzVaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEzVault {
    return new Contract(address, _abi, signerOrProvider) as IEzVault;
  }
}
